# Generated by Django 6.0 on 2026-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.CharField(unique=True),
        ),
    ]
