# Generated by Django 6.0 on 2025-12-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='passw',
            field=models.IntegerField(default=12),
        ),
    ]
