# Generated by Django 6.0 on 2026-01-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(unique=True),
        ),
    ]
