# Generated by Django 6.0 on 2026-01-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_department_students'),
        ('students', '0004_alter_student_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deparment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department'),
        ),
    ]
