# Generated by Django 6.0 on 2026-01-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_attendance_status'),
        ('students', '0004_alter_student_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deparment',
            field=models.ForeignKey(default='b.tech', on_delete=django.db.models.deletion.CASCADE, to='courses.department'),
            preserve_default=False,
        ),
    ]
