# Generated by Django 6.0 on 2026-01-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_deparment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='deparment',
            new_name='department',
        ),
    ]
