# Generated by Django 6.0 on 2025-12-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
