# Generated by Django 6.0 on 2026-01-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_attendance_status'),
        ('students', '0005_student_deparment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deparment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.department'),
        ),
    ]
