# Generated by Django 6.0 on 2025-12-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_id',
            field=models.IntegerField(choices=[(1, 'B.tech'), (2, 'B.com'), (3, 'B.A')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(choices=[('B.tech', 'B.tech'), ('B.com', 'B.com'), ('B.A', 'B.A')], max_length=50),
        ),
    ]
