# Generated by Django 6.0 on 2026-01-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dep_id',
        ),
    ]
