# Generated by Django 6.0 on 2026-01-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_department_dep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='students',
        ),
    ]
