# Generated by Django 6.0 on 2026-01-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_department_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='teacher',
            new_name='hod',
        ),
    ]
